package com.example.memorizerbackend.db.memory;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;


@Controller // This means that this class is a Controller
@RequestMapping(path="/memory") // This means URL's start with /demo (after Application path)
public class MemoryController {
  @Autowired // This means to get the bean called userRepository
         // Which is auto-generated by Spring, we will use it to handle the data
  private MemoryRepository memoryRepository;

   @PostMapping(path="/add") // Map ONLY POST Requests
   public @ResponseBody String addNewMemory (@RequestBody Memory memory) {
     memoryRepository.save(memory);
     return "Saved";
   }

  @GetMapping(path="/all")
  public @ResponseBody Iterable<Memory> getAllMemory() {
    // This returns a JSON or XML with the users
    return memoryRepository.findAll();
  }
}
